package ServeurBancaire;


/**
* ServeurBancaire/BankCostumerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, December 4, 2016 3:55:12 PM CET
*/

public abstract class BankCostumerPOA extends org.omg.PortableServer.Servant
 implements ServeurBancaire.BankCostumerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("deposit", new java.lang.Integer (0));
    _methods.put ("withdraw", new java.lang.Integer (1));
    _methods.put ("balance", new java.lang.Integer (2));
    _methods.put ("create", new java.lang.Integer (3));
    _methods.put ("destroy", new java.lang.Integer (4));
    _methods.put ("transfert", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServeurBancaire/BankCostumer/deposit
       {
         int id = in.read_ulong ();
         int amount = in.read_ulong ();
         this.deposit (id, amount);
         out = $rh.createReply();
         break;
       }

       case 1:  // ServeurBancaire/BankCostumer/withdraw
       {
         int id = in.read_ulong ();
         int amount = in.read_ulong ();
         this.withdraw (id, amount);
         out = $rh.createReply();
         break;
       }

       case 2:  // ServeurBancaire/BankCostumer/balance
       {
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.balance (id);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // ServeurBancaire/BankCostumer/create
       {
         String name = in.read_string ();
         int amount = in.read_ulong ();
         int $result = (int)0;
         $result = this.create (name, amount);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // ServeurBancaire/BankCostumer/destroy
       {
         int a = in.read_ulong ();
         this.destroy (a);
         out = $rh.createReply();
         break;
       }

       case 5:  // ServeurBancaire/BankCostumer/transfert
       {
         int from = in.read_long ();
         int bank_id = in.read_long ();
         String name = in.read_string ();
         int amount = in.read_ulong ();
         this.transfert (from, bank_id, name, amount);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServeurBancaire/BankCostumer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BankCostumer _this() 
  {
    return BankCostumerHelper.narrow(
    super._this_object());
  }

  public BankCostumer _this(org.omg.CORBA.ORB orb) 
  {
    return BankCostumerHelper.narrow(
    super._this_object(orb));
  }


} // class BankCostumerPOA
