package ServeurBancaire;


/**
* ServeurBancaire/BankCustomer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Thursday, December 8, 2016 4:16:16 PM CET
*/

public interface BankCustomer extends BankCustomerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BankCustomer
