package ServeurBancaire;

/**
* ServeurBancaire/BankCostumerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, December 4, 2016 3:55:12 PM CET
*/

public final class BankCostumerHolder implements org.omg.CORBA.portable.Streamable
{
  public ServeurBancaire.BankCostumer value = null;

  public BankCostumerHolder ()
  {
  }

  public BankCostumerHolder (ServeurBancaire.BankCostumer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServeurBancaire.BankCostumerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServeurBancaire.BankCostumerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServeurBancaire.BankCostumerHelper.type ();
  }

}
