package ServeurBancaire;


/**
* ServeurBancaire/BankCostumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, December 4, 2016 3:55:12 PM CET
*/

public interface BankCostumerOperations 
{
  void deposit (int id, int amount);
  void withdraw (int id, int amount);
  int balance (int id);
  int create (String name, int amount);
  void destroy (int a);
  void transfert (int from, int bank_id, String name, int amount);
} // interface BankCostumerOperations
