package ServeurBancaire;


/**
* ServeurBancaire/BankCostumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Sunday, December 4, 2016 3:55:12 PM CET
*/

public interface BankCostumer extends BankCostumerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BankCostumer
