package InterBank;


/**
* InterBank/_BankTransactStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interbank.idl
* Thursday, December 8, 2016 4:12:42 PM CET
*/

public class _BankTransactStub extends org.omg.CORBA.portable.ObjectImpl implements InterBank.BankTransact
{

  public void saveTransact (int bank_from, int from, int bank_id, int to, int amount)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("saveTransact", true);
                $out.write_ulong (bank_from);
                $out.write_ulong (from);
                $out.write_ulong (bank_id);
                $out.write_ulong (to);
                $out.write_ulong (amount);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                saveTransact (bank_from, from, bank_id, to, amount        );
            } finally {
                _releaseReply ($in);
            }
  } // saveTransact

  public InterBank.Transact[] passTransacts (int bank_id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("passTransacts", true);
                $out.write_ulong (bank_id);
                $in = _invoke ($out);
                InterBank.Transact $result[] = InterBank.TransactsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return passTransacts (bank_id        );
            } finally {
                _releaseReply ($in);
            }
  } // passTransacts

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:InterBank/BankTransact:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _BankTransactStub
