package InterBank;


/**
* InterBank/BankTransactPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interbank.idl
* Thursday, December 8, 2016 4:12:42 PM CET
*/

public abstract class BankTransactPOA extends org.omg.PortableServer.Servant
 implements InterBank.BankTransactOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("saveTransact", new java.lang.Integer (0));
    _methods.put ("passTransacts", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // InterBank/BankTransact/saveTransact
       {
         int bank_from = in.read_ulong ();
         int from = in.read_ulong ();
         int bank_id = in.read_ulong ();
         int to = in.read_ulong ();
         int amount = in.read_ulong ();
         this.saveTransact (bank_from, from, bank_id, to, amount);
         out = $rh.createReply();
         break;
       }

       case 1:  // InterBank/BankTransact/passTransacts
       {
         int bank_id = in.read_ulong ();
         InterBank.Transact $result[] = null;
         $result = this.passTransacts (bank_id);
         out = $rh.createReply();
         InterBank.TransactsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:InterBank/BankTransact:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BankTransact _this() 
  {
    return BankTransactHelper.narrow(
    super._this_object());
  }

  public BankTransact _this(org.omg.CORBA.ORB orb) 
  {
    return BankTransactHelper.narrow(
    super._this_object(orb));
  }


} // class BankTransactPOA
