package InterBank;


/**
* InterBank/BankTransact.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interbank.idl
* Thursday, December 8, 2016 4:12:42 PM CET
*/

public interface BankTransact extends BankTransactOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BankTransact
