package InterBank;

/**
* InterBank/TransactHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interbank.idl
* Thursday, December 8, 2016 4:12:42 PM CET
*/

public final class TransactHolder implements org.omg.CORBA.portable.Streamable
{
  public InterBank.Transact value = null;

  public TransactHolder ()
  {
  }

  public TransactHolder (InterBank.Transact initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InterBank.TransactHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InterBank.TransactHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InterBank.TransactHelper.type ();
  }

}
