package InterBank;


/**
* InterBank/TransactsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interbank.idl
* Thursday, December 8, 2016 4:12:42 PM CET
*/

public final class TransactsHolder implements org.omg.CORBA.portable.Streamable
{
  public InterBank.Transact value[] = null;

  public TransactsHolder ()
  {
  }

  public TransactsHolder (InterBank.Transact[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InterBank.TransactsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InterBank.TransactsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InterBank.TransactsHelper.type ();
  }

}
