package InterBank;


/**
* InterBank/TransactsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interbank.idl
* Thursday, December 8, 2016 4:12:42 PM CET
*/

abstract public class TransactsHelper
{
  private static String  _id = "IDL:InterBank/Transacts:1.0";

  public static void insert (org.omg.CORBA.Any a, InterBank.Transact[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static InterBank.Transact[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = InterBank.TransactHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (InterBank.TransactsHelper.id (), "Transacts", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static InterBank.Transact[] read (org.omg.CORBA.portable.InputStream istream)
  {
    InterBank.Transact value[] = null;
    int _len0 = istream.read_long ();
    value = new InterBank.Transact[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = InterBank.TransactHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, InterBank.Transact[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      InterBank.TransactHelper.write (ostream, value[_i0]);
  }

}
