module InterBanqueServeur{


	interface InterBanque{
		
	};

	interface BanqueCostumerServices{
		long authentifier(in string c_id, in string password);
		void debiter(in string c_id, in double montant);
		void crediter(in string c_id, in double montant);
		void transferer(in string c_id_sender, in string c_id_receiver, in double montant);
		double getSolde(in string c_id);
		long creerCompte(in string nom,in string solde);
		string getID(in string nom);
		Compte getCompte(in string c_id);
	}

};
